language: java
install: true

before_install:
  - chmod +x gradlew

stages:
  - name: build
  - name: snapshot
    if: branch = develop
  - name: release
    if: branch = master

jobs:
  include:
  - stage: build
    script:
    - gpg --import keyring.asc
    - "./gradlew build"
  - stage: snapshot
    script:
    - gpg --import keyring.asc
    - "./gradlew artifactoryPublish -x test -Dbuild.number=$TRAVIS_BUILD_NUMBER"
  - stage: release
    script:
    - gpg --import keyring.asc
    - "./gradlew bintrayUpload -x test -Drelease=true -Dbuild.number=$TRAVIS_BUILD_NUMBER"
