language: java
install: true

before_install:
 - chmod +x gradlew

stages:
  - name: build
  - name: snapshot
    if: branch = develop
  - name: release
    if: branch = master


jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: snapshot
      script: ./gradlew artifactoryPublish -x test -Dbuild.number=$TRAVIS_BUILD_NUMBER
    - stage: release
      script: ./gradlew bintrayUpload -x test -Drelease=true -Dbuild.number=$TRAVIS_BUILD_NUMBER
