language: java
install: true
before_install:
#- openssl aes-256-cbc -K $encrypted_d328b9e20119_key -iv $encrypted_d328b9e20119_iv
#  -in keyring.gpg.enc -out keyring.gpg -d
- chmod +x gradlew
stages:
- name: build
- name: snapshot
  if: branch = develop
- name: release
  if: branch = master
jobs:
  include:
  - stage: build
    script:
    - "./gradlew build --info"
  - stage: snapshot
    script:
    - "./gradlew artifactoryPublish -x test -Dbuild.number=$TRAVIS_BUILD_NUMBER --info"
  - stage: release
    script:
    - "./gradlew -Prelease.useLastTag=true final --info"
