language: java
install: true

before_install:
  - chmod +x gradlew

stages:
  - name: snapshot
    if: branch = master AND tag IS NOT present
  - name: release
    if: branch = master AND tag IS present

jobs:
  include:
  - stage: snapshot
    script:
    - "./gradlew snapshot artifactoryPublish --info"
  - stage: release
    script:
    - "./gradlew -Prelease.useLastTag=true final --info"
